apiVersion: v1
kind: Service
metadata:
  name: goserver-service
  labels:
    app: goserver
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: goserver
    tier: backend
  ports:
  - protocol: TCP
    port: 8080 # porta do service
    targetPort: 8080 # porta do meu container
    name: goserver-port